server {
    listen 80;

    location = / {
        return 301 /energy_tracker/;
    }

    # Proxy to Full-stack Backend for energy tracking API
    location /energy_tracker/api/ {
        proxy_pass http://localhost:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /energy_tracker/ {
        alias /usr/share/nginx/html/energy_tracker/;
        index index.html;
        try_files $uri $uri/ /energy_tracker/index.html;
    }

    error_page 404 /energy_tracker/index.html;
}
