server {
    listen 80;

    location = / {
        return 301 /energy_tracker/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /energy_tracker/index.html;
    }

    error_page 404 /energy_tracker/index.html;
}
